### PR TITLE
Load without side effects

### LINKED ISSUE #15: Remove key settings from the top-level
As mentioned here: https://github.com/ch11ng/exwm/issues/708#issuecomment-587416861,
you should remove the key bindings from the top-level.
I suggest you add those bindings as a suggestion in the README.

### PR DESCRIPTION
**Pull request by josephmturner**
Resolves #15.

Thank you!!

### CODE REVIEW

**Comment by josephmturner** [comment]
Hi @agzam! Thanks for merging #26 and #27.  I rebased this branch on top of master and force-pushed to my fork.

@Ambrevar does this PR resolve your concern in #15?

**Review by agzam — APPROVED** [review]

**Comment by agzam** [comment]
Hey friends. I approved it, but it's been a while since the last time I used EXWM. I am planning to install it again sometime soon. I can't test this very quickly, so merge it at your own volition. Thanks!

**Comment by josephmturner** [comment]
Hi @agzam - I'd be happy to take over maintainership of `exwm-edit` if you like.

**Comment by josephmturner** [comment]
Hi @agzam - I see you gave a thumbs up reaction to my comment about taking over maintainership.  Thank you!!

Would you mind if I moved the repository over to SourceHut, where I keep my other packages?

https://git.sr.ht/~breatheoutbreathein

**Comment by agzam** [comment]
> Would you mind if I moved the repository over to SourceHut, where I keep my other packages?

Feel free to fork it, but the origin repo has to stay here, since that's how it's listed on MELPA.

**Comment by josephmturner** [comment]
> > 
> 
> Feel free to fork it, but the origin repo has to stay here, since that's how the package is listed on MELPA.

I'm willing to take care of changing the package repository in MELPA.  Would that be alright with you?

**Comment by agzam** [comment]
> I'm willing to take care of changing the package repository in MELPA. Would that be alright with you?

No, it wouldn't. Sourcehut is known for being unreliable and slow. I know, GitHub is bad and controlled by the Big Evil Corp, etc., yet there's tons of Elisp code hosted on it. 
GitHub has higher visibility, excellent community interactions, and advanced features which make projects easier to manage and maintain. I don't see any reason today to move the package source elsewhere. That may change someday, but for now, the package lives here.

I can't stop you from forking the project and making it better than the original and hosting that version anywhere you want. But this one stays here for now. I frankly don't understand why you want to move it; it sounds more like an aggressive 'takeover' rather than collaboration.

**Comment by josephmturner** [comment]
Thanks for making your decision clear.  I'm willing to continue development here on GitHub.

Still, I'd like to respond to your points about SourceHut.  Aside from the DDOS outage a few months ago, SourceHut has been fast and reliable IME.  Of course, SourceHut has less resources for its build farm, but I think that's not relevant in `exwm-edit`s case.  Also, I try to avoid using a web browser for tasks which I can handle in Emacs, and SourceHut's email workflow allows me to do that when reviewing and merging patches, whereas GitHub requires that I log into the webapp to merge PRs.

I appreciate your willingness to add me as a maintainer!  I'll go ahead and merge #25 and #28 as my first action.

**Comment by josephmturner** [comment]
Oh!  I see you did add me as maintainer already!  Okay - I'll review these PRs once more and merge.

**Comment by agzam** [comment]
> SourceHut has been fast and reliable ... I think that's not relevant

Dude _[I'm using the word here as an exclamation, like "Jesus"],_ it's not about GitHub vs some other forge, it's about "respecting the inventor". Look, years ago I came up with this tiny silly thing. Then people learned about it and I had to support it. There were times when I'd wake up in the middle of the night, thinking if I broke someone's workflow earlier. My name's attached to it and I still feel responsible for what I've made those years ago. And if suddenly someone comes, saying like: "Thanks grandpa, I'll take it from here, and you can forget it even existed. Enjoy your retirement..." Of course that would inevitably raise my eyebrow.

I don't have sentimental attachment to any code I write, especially something small like this package. But I chose to shit this thing over in a GitHub repo. The rules of OSS are such that you can change that shit anyway you like. You can mix it with some other shit. You can add more shit on top of it. As long that all is for the improvement of the whole shit, I would always approve it. But please, don't move this shit anywhere else, because I like this shit to stay here for now. Thank you.

**Comment by agzam** [comment]
btw. you can use [wandersoncferreira/code-review](https://github.com/wandersoncferreira/code-review) to review GitHub PRs in Emacs.

**Pull request merged**
